version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      - /home/docker/docker_learning/frontend/:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - /home/docker/docker_learning/frontend/:/app
    command: ["npm", "test"]
